language: python
sudo: required
env:
  - CODECOV_TOKEN: "da32b183-0d8b-4dc2-9bf9-e1743a39b2c8"
services:
  - docker
python:
  - "2.7"
  - "3.6"
  - "nightly"
# command to install dependencies
install:
  - docker-compose up -d
  - pip install .
  - pip install -r requirements-test.txt
  - docker exec -it wpapipython_woocommerce_1 bash -c 'until [ -f .done ]; do sleep 1; done; echo "complete"'
# command to run tests
script:
  - py.test --cov=wordpress tests.py
after_success:
  - codecov
