language: python
sudo: required
services: 
  - docker
python:
  - "2.7"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - pip install .
  - pip install -r requirements-test.txt
  - docker-compose up
# command to run tests
script:
  - pytest
